import type { Metadata } from "next";
import "./globals.css";
import { Footer, Header } from "@/components";
import { Pop } from "./fonts";

export const metadata: Metadata = {
  title: "Assignment",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={Pop.className}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
